---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- helm-release.yaml
- helm-repository.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_externalsecrets.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_secretstores.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_clusterexternalsecrets.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_clustersecretstores.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_acraccesstokens.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_awssmsecrets.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_gcpsecrets.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_ibmsecrets.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_vaultsecrets.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crd/bases/external-secrets.io_onepasswordsecrets.yaml